#!/usr/bin/env python
"""SUPERSEDED by generate_notebooks.py -- kept for reference only.

One-time migration script that added eddy-current and higher-harmonics sections
to MC62 analysis notebooks. MC62 notebooks are now fully generated by the
unified generate_notebooks.py.
"""
from __future__ import annotations

import json
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NB_BASE = ROOT / "rotating_coil_analyzer" / "notebooks" / "LEAR_MC62"


# ── helpers ─────────────────────────────────────────────────────────
def _cell(cell_type: str, source: str) -> dict:
    """Build a minimal Jupyter cell dict."""
    # Jupyter convention: every line ends with \n except the last
    lines = source.split("\n")
    src_list = [line + "\n" for line in lines[:-1]] + [lines[-1]]
    c = {
        "cell_type": cell_type,
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "source": src_list,
    }
    if cell_type == "code":
        c["execution_count"] = None
        c["outputs"] = []
    return c


def _find_cell(cells: list[dict], heading_prefix: str) -> int | None:
    """Find the index of the first cell whose source starts with *heading_prefix*."""
    for i, cell in enumerate(cells):
        src = "".join(cell["source"]) if isinstance(cell["source"], list) else cell["source"]
        if src.lstrip().startswith(heading_prefix):
            return i
    return None


def _find_cell_containing(cells: list[dict], needle: str) -> int | None:
    """Find the first cell whose source contains *needle*."""
    for i, cell in enumerate(cells):
        src = "".join(cell["source"]) if isinstance(cell["source"], list) else cell["source"]
        if needle in src:
            return i
    return None


# ── new cells ───────────────────────────────────────────────────────

def build_higher_harmonics_cells() -> list[dict]:
    """Higher Harmonics Overview: b4..bH, a2..aH statistics table."""
    md = _cell("markdown", """\
## Higher Harmonics Overview

Statistics of all measured harmonics at key operating points (peak |I|).
Normal harmonics b4\u2026bH and skew harmonics a2\u2026aH are shown as mean \u00b1 std
across settled turns, for the Integral (R45) PCB.""")

    code = _cell("code", """\
# --- Higher harmonics statistics at peak current ---
_peak_mask = summ_int["I_nom"].abs() == summ_int["I_nom"].abs().max()
_peak = summ_int[_peak_mask]

# Detect available harmonic columns
_bn_cols = sorted([c for c in summ_int.columns if c.endswith("_mean")
                   and (c.startswith("b") or c.startswith("a"))
                   and c not in ("b2_mean", "b3_mean")],
                  key=lambda c: (c[0], int(c.split("_")[0][1:])))

if _peak.empty or not _bn_cols:
    print("No peak-current data or harmonic columns found -- skipping.")
else:
    rows = []
    for col in _bn_cols:
        base = col.replace("_mean", "")
        std_col = base + "_std"
        mean_val = _peak[col].values[0]
        std_val = _peak[std_col].values[0] if std_col in _peak.columns else float("nan")
        rows.append({"Harmonic": base, "Mean [units]": mean_val, "Std [units]": std_val})
    _htable = pd.DataFrame(rows)
    print("Higher harmonics at peak |I| (Integral PCB):")
    print(_htable.to_string(index=False, float_format="%.3f"))

    # Bar chart
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    _bn_only = [r for r in rows if r["Harmonic"].startswith("b")]
    _an_only = [r for r in rows if r["Harmonic"].startswith("a")]
    for ax, data, title in [(axes[0], _bn_only, "Normal (b_n)"),
                            (axes[1], _an_only, "Skew (a_n)")]:
        if not data:
            ax.set_visible(False)
            continue
        labels = [d["Harmonic"] for d in data]
        vals = [abs(d["Mean [units]"]) for d in data]
        ax.bar(labels, vals, color="steelblue", alpha=0.7)
        ax.set_ylabel("|value| [units]")
        ax.set_title(title)
        ax.set_yscale("log")
        ax.tick_params(axis="x", rotation=45)
    fig.suptitle(f"Higher harmonics at I = {_peak['I_nom'].values[0]:.0f} A", y=1.02)
    fig.tight_layout()
    plt.show()""")
    return [md, code]


def build_eddy_cells(*, is_streaming: bool) -> list[dict]:
    """Build the eddy-current settling section cells.

    Parameters
    ----------
    is_streaming : bool
        True for 03/04 (streaming, 2 Hz), False for 01/02 (file-based, 1 Hz).
    """
    cells: list[dict] = []

    # -- 0. Config & alias --
    if is_streaming:
        config_src = """\
# ── Eddy-current configuration ──────────────────────────────────────
from scipy.optimize import curve_fit
from rotating_coil_analyzer.analysis.utility_functions import (
    eddy_model, fit_eddy_per_run,
)

MIN_I_FOR_FIT = 10.0   # minimum |I_nom| [A] for fitting
# T_PER_TURN already defined in config

# Use Integral PCB data for eddy analysis
df_eddy = df_int.copy()
print(f"Eddy-current analysis: {len(df_eddy)} turns, "
      f"{df_eddy['run_id'].nunique()} runs")"""
    else:
        config_src = """\
# ── Eddy-current configuration ──────────────────────────────────────
from scipy.optimize import curve_fit
from rotating_coil_analyzer.analysis.utility_functions import (
    eddy_model, fit_eddy_per_run,
)

MIN_I_FOR_FIT = 10.0   # minimum |I_nom| [A] for fitting
T_PER_TURN = 1.0       # 1 Hz rotation → 1.0 s per turn

# Use Integral PCB data for eddy analysis
df_eddy = df_int.copy()
print(f"Eddy-current analysis: {len(df_eddy)} turns, "
      f"{df_eddy['run_id'].nunique()} runs")"""

    cells.append(_cell("markdown", """\
---

## Eddy-Current Settling Analysis

The following sections analyse the eddy-current transient on staircase plateaus.
All analysis uses the **Integral (R45) PCB** data (`df_int`) already processed above."""))
    cells.append(_cell("code", config_src))

    # -- 1. Raw settling curves --
    cells.append(_cell("markdown", """\
### Raw Settling Curves -- B1 vs Turn Number

Turn-by-turn B1 for all runs.  The exponential settling after each current step
is visible in the first ~100 turns.  Runs are colored by nominal current."""))

    cells.append(_cell("code", """\
cmap = plt.cm.coolwarm
_I_noms = sorted(df_eddy["I_nom"].unique())
_norm_c = plt.Normalize(min(_I_noms), max(_I_noms))

fig, axes = plt.subplots(2, 1, figsize=(12, 6), sharex=True)

# Panel 1: positive-current runs
ax = axes[0]
for run_id in sorted(df_eddy["run_id"].unique()):
    rdf = df_eddy[(df_eddy["run_id"] == run_id) & df_eddy["ok_main"]]
    if rdf.empty or rdf["I_nom"].iloc[0] <= 0:
        continue
    I_nom = rdf["I_nom"].iloc[0]
    ax.plot(rdf["turn_in_run"], rdf["B1_T"], lw=0.5,
            color=cmap(_norm_c(I_nom)), alpha=0.7)
ax.set_ylabel("B1 [T]")
ax.set_title("Positive current")
ax.grid(True, alpha=0.3)

# Panel 2: negative-current runs
ax = axes[1]
for run_id in sorted(df_eddy["run_id"].unique()):
    rdf = df_eddy[(df_eddy["run_id"] == run_id) & df_eddy["ok_main"]]
    if rdf.empty or rdf["I_nom"].iloc[0] >= 0:
        continue
    I_nom = rdf["I_nom"].iloc[0]
    ax.plot(rdf["turn_in_run"], rdf["B1_T"], lw=0.5,
            color=cmap(_norm_c(I_nom)), alpha=0.7)
ax.set_ylabel("B1 [T]")
ax.set_xlabel("Turn in run")
ax.set_title("Negative current")
ax.grid(True, alpha=0.3)

fig.suptitle("Raw settling curves -- B1 vs turn number", y=1.01)
fig.tight_layout()
plt.show()"""))

    # -- 2. Exponential fits --
    cells.append(_cell("markdown", """\
### Exponential Fit -- Tau for Each Plateau

Fit the single-exponential eddy model $B_1(t) = B_\\infty + A\\,e^{-t/\\tau}$
to each run using `fit_eddy_per_run()`.  Results are classified as GOOD
(R\\u00b2 \\u2265 0.9), MARGINAL, WEAK_SIGNAL, or FIT_FAILED."""))

    cells.append(_cell("code", """\
_fit_results = []
for run_id in sorted(df_eddy["run_id"].unique()):
    rdf = df_eddy[(df_eddy["run_id"] == run_id) & df_eddy["ok_main"]].sort_values("turn_in_run")
    if rdf.empty:
        continue
    I_nom = rdf["I_nom"].iloc[0]
    if abs(I_nom) < MIN_I_FOR_FIT:
        continue
    branch = rdf["branch"].iloc[0]
    I_mean = rdf["I_mean"].values if "I_mean" in rdf.columns else None
    res = fit_eddy_per_run(
        turns=rdf["turn_in_run"].values.astype(float),
        B1=rdf["B1_T"].values,
        run_id=run_id, I_nom=I_nom, branch=branch,
        I_mean=I_mean,
    )
    _fit_results.append(res)

df_fits_all = pd.DataFrame([
    {"run_id": r.run_id, "I_nom": r.I_nom, "branch": r.branch,
     "B_inf": r.B_inf, "A": r.A, "tau": r.tau, "tau_err": r.tau_err,
     "tau_s": r.tau * T_PER_TURN, "tau_err_s": r.tau_err * T_PER_TURN,
     "r2": r.r2, "n_turns": r.n_turns, "quality": r.quality, "reason": r.reason}
    for r in _fit_results
])

df_fits = df_fits_all[df_fits_all["quality"] == "GOOD"].copy()
print(f"Fits: {len(df_fits)} GOOD / {len(df_fits_all)} total")
print()

# Summary table
print(f"{'Run':>4s} {'I [A]':>8s} {'Branch':>10s} {'tau [s]':>8s} "
      f"{'tau_err':>8s} {'R\\u00b2':>8s} {'Quality':>12s}")
print("-" * 70)
for _, r in df_fits_all.iterrows():
    print(f"{r['run_id']:4.0f} {r['I_nom']:+8.1f} {r['branch']:>10s} "
          f"{r['tau_s']:8.2f} {r['tau_err_s']:8.2f} {r['r2']:8.4f} "
          f"{r['quality']:>12s}")"""))

    # -- Fit grid plot --
    cells.append(_cell("code", """\
# Plot fitted curves in a grid
_n_runs = len(df_fits_all)
_n_cols = min(8, _n_runs)
_n_rows = max(1, (_n_runs + _n_cols - 1) // _n_cols)

fig, axes = plt.subplots(_n_rows, _n_cols, figsize=(16, 2.2 * _n_rows))
_axes_flat = np.atleast_1d(axes).flatten()

for idx, (_, row) in enumerate(df_fits_all.iterrows()):
    ax = _axes_flat[idx]
    rdf = df_eddy[(df_eddy["run_id"] == row["run_id"]) & df_eddy["ok_main"]].sort_values("turn_in_run")
    turns = rdf["turn_in_run"].values.astype(float)
    B1 = rdf["B1_T"].values
    ax.plot(turns, B1 * 1e3, ".", ms=1, alpha=0.3, color="tab:blue")

    if row["quality"] in ("GOOD", "MARGINAL") and np.isfinite(row["tau"]):
        t_fit = np.linspace(turns.min(), turns.max(), 200)
        B_fit = eddy_model(t_fit, row["B_inf"], row["A"], row["tau"])
        ax.plot(t_fit, B_fit * 1e3, "r-", lw=1)

    ax.set_title(f"R{row['run_id']:.0f} I={row['I_nom']:+.0f}A\\n"
                 f"\\u03c4={row['tau_s']:.1f}s R\\u00b2={row['r2']:.3f}",
                 fontsize=7)
    ax.tick_params(labelsize=6)

for idx in range(_n_runs, len(_axes_flat)):
    _axes_flat[idx].set_visible(False)

fig.suptitle("Single-exponential fits -- B1 settling per plateau", y=1.01)
fig.tight_layout()
plt.show()"""))

    # -- 3. Tau vs current --
    cells.append(_cell("markdown", """\
### Tau vs Current -- The Permeability Effect

The settling time constant depends on the iron permeability $\\mu_r(H)$:
$$\\tau \\propto \\mu_r(H) \\cdot \\sigma \\cdot d^2$$
At low current (high $\\mu_r$), $\\tau$ is larger.  At high current (saturation),
$\\mu_r$ drops and $\\tau$ decreases."""))

    cells.append(_cell("code", """\
_branch_colors = {"ascending": "tab:blue", "descending": "tab:red"}

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# (a) tau (seconds) vs |I|
ax = axes[0]
for branch, col in _branch_colors.items():
    mask = df_fits["branch"] == branch
    ax.scatter(df_fits.loc[mask, "I_nom"].abs(), df_fits.loc[mask, "tau_s"],
               c=col, label=branch, s=30, alpha=0.7)
ax.set_xlabel("|I| [A]")
ax.set_ylabel("\\u03c4 [s]")
ax.set_title("Settling time constant vs current")
ax.legend()
ax.grid(True, alpha=0.3)

# (b) tau (turns) vs |I|
ax = axes[1]
for branch, col in _branch_colors.items():
    mask = df_fits["branch"] == branch
    ax.scatter(df_fits.loc[mask, "I_nom"].abs(), df_fits.loc[mask, "tau"],
               c=col, label=branch, s=30, alpha=0.7)
ax.set_xlabel("|I| [A]")
ax.set_ylabel("\\u03c4 [turns]")
ax.set_title("Settling time constant (turn units)")
ax.legend()
ax.grid(True, alpha=0.3)

fig.tight_layout()
plt.show()

if len(df_fits) > 0:
    print(f"Tau range: {df_fits['tau_s'].min():.1f} -- {df_fits['tau_s'].max():.1f} s "
          f"({df_fits['tau'].min():.0f} -- {df_fits['tau'].max():.0f} turns)")"""))

    # -- 4. Settling bias --
    cells.append(_cell("markdown", """\
### Settling Bias in b2, b3

The eddy-current transient affects not just $B_1$ but all harmonics.  The
**settling bias** quantifies how much a harmonic deviates from its fully-settled
value as a function of position within the plateau."""))

    cells.append(_cell("code", """\
fig, axes = plt.subplots(3, 1, figsize=(12, 7), sharex=True)

_show_runs = [r for _, r in df_fits.iterrows()]
_show_runs = _show_runs[::max(1, len(_show_runs) // 8)]  # subsample for readability

for quantity, col_name, ax, ylabel in [
    ("B1", "B1_T", axes[0], "B1 deviation [units, 1e-4 rel.]"),
    ("b2", "b2_units", axes[1], "b2 deviation [units]"),
    ("b3", "b3_units", axes[2], "b3 deviation [units]"),
]:
    for row in _show_runs:
        run_id = row["run_id"]
        rdf = df_eddy[(df_eddy["run_id"] == run_id) & df_eddy["ok_main"]].sort_values("turn_in_run")
        if rdf.empty or col_name not in rdf.columns:
            continue
        vals = rdf[col_name].values
        ref = vals[-N_LAST_TURNS:].mean() if len(vals) >= N_LAST_TURNS else vals[-10:].mean()
        if quantity == "B1":
            dev = (vals - ref) / abs(ref) * 1e4 if abs(ref) > 1e-9 else vals - ref
        else:
            dev = vals - ref
        ax.plot(rdf["turn_in_run"].values, dev, lw=0.5, alpha=0.6,
                label=f"R{run_id:.0f} I={row['I_nom']:+.0f}")
    ax.set_ylabel(ylabel)
    ax.axhline(0, color="k", lw=0.5)
    ax.grid(True, alpha=0.3)

axes[0].legend(fontsize=6, ncol=4, loc="upper right")
axes[-1].set_xlabel("Turn in run")
fig.suptitle("Settling bias -- deviation from settled mean", y=1.01)
fig.tight_layout()
plt.show()"""))

    # -- 5. N_LAST sensitivity --
    cells.append(_cell("markdown", """\
### N_LAST Sensitivity Study

Scan the averaging window (`N_LAST_TURNS`) and show how the mean B1 error
and b3 error converge.  The vertical red line marks the chosen `N_LAST_TURNS`."""))

    if is_streaming:
        n_last_range = "np.arange(50, 701, 10)"
    else:
        n_last_range = "np.arange(20, 331, 5)"

    cells.append(_cell("code", f"""\
_n_last_values = {n_last_range}
_study_runs = df_fits["run_id"].unique()

_results_sweep = []
for _nl in _n_last_values:
    _B1_errs, _b3_errs = [], []
    for run_id in _study_runs:
        rdf = df_eddy[(df_eddy["run_id"] == run_id) & df_eddy["ok_main"]].sort_values("turn_in_run")
        if len(rdf) < _nl + 20:
            continue
        # "True" settled value: last 20 turns
        B1_true = rdf["B1_T"].values[-20:].mean()
        B1_est = rdf["B1_T"].values[-_nl:].mean()
        _B1_errs.append((B1_est - B1_true) / abs(B1_true) * 1e4)

        if "b3_units" in rdf.columns:
            b3_true = rdf["b3_units"].values[-20:].mean()
            b3_est = rdf["b3_units"].values[-_nl:].mean()
            _b3_errs.append(b3_est - b3_true)

    if _B1_errs:
        _results_sweep.append({{
            "N_LAST": _nl,
            "B1_bias_units": np.mean(_B1_errs),
            "B1_bias_std": np.std(_B1_errs),
            "b3_bias_units": np.mean(_b3_errs) if _b3_errs else np.nan,
            "b3_bias_std": np.std(_b3_errs) if _b3_errs else np.nan,
        }})

_df_sweep = pd.DataFrame(_results_sweep)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

ax = axes[0]
ax.fill_between(_df_sweep["N_LAST"],
                _df_sweep["B1_bias_units"] - _df_sweep["B1_bias_std"],
                _df_sweep["B1_bias_units"] + _df_sweep["B1_bias_std"],
                alpha=0.2, color="tab:blue")
ax.plot(_df_sweep["N_LAST"], _df_sweep["B1_bias_units"], ".-", color="tab:blue")
ax.axhline(0, color="k", lw=0.5)
ax.axvline(N_LAST_TURNS, color="red", ls="--", lw=1, label=f"N_LAST = {{N_LAST_TURNS}}")
ax.set_xlabel("N_LAST")
ax.set_ylabel("B1 bias [units, 1e-4 rel.]")
ax.set_title("B1 systematic bias vs averaging window")
ax.legend()
ax.grid(True, alpha=0.3)

ax = axes[1]
if _df_sweep["b3_bias_units"].notna().any():
    ax.fill_between(_df_sweep["N_LAST"],
                    _df_sweep["b3_bias_units"] - _df_sweep["b3_bias_std"],
                    _df_sweep["b3_bias_units"] + _df_sweep["b3_bias_std"],
                    alpha=0.2, color="tab:green")
    ax.plot(_df_sweep["N_LAST"], _df_sweep["b3_bias_units"], ".-", color="tab:green")
ax.axhline(0, color="k", lw=0.5)
ax.axvline(N_LAST_TURNS, color="red", ls="--", lw=1, label=f"N_LAST = {{N_LAST_TURNS}}")
ax.set_xlabel("N_LAST")
ax.set_ylabel("b3 bias [units]")
ax.set_title("b3 systematic bias vs averaging window")
ax.legend()
ax.grid(True, alpha=0.3)

fig.tight_layout()
plt.show()"""))

    # -- 6. Double-exponential --
    cells.append(_cell("markdown", """\
### Double-Exponential Fit Comparison

A double-exponential model captures two eddy-current decay time scales:
$$B_1(t) = B_\\infty + A_1\\,e^{-t/\\tau_1} + A_2\\,e^{-t/\\tau_2}$$
Compare R\\u00b2 improvement over the single-exponential model."""))

    cells.append(_cell("code", """\
def _double_eddy(t, B_inf, A1, tau1, A2, tau2):
    return B_inf + A1 * np.exp(-t / tau1) + A2 * np.exp(-t / tau2)

_dbl_records = []
for _, srow in df_fits_all.iterrows():
    run_id = int(srow["run_id"])
    rdf = df_eddy[(df_eddy["run_id"] == run_id) & df_eddy["ok_main"]].sort_values("turn_in_run")
    if rdf.empty:
        continue
    turns = rdf["turn_in_run"].values.astype(float)
    B1 = rdf["B1_T"].values
    r2_single = srow["r2"]
    if not np.isfinite(srow["tau"]):
        continue

    p0 = [srow["B_inf"], srow["A"] * 0.5, srow["tau"] / 3,
           srow["A"] * 0.5, srow["tau"] * 2]
    try:
        popt, _ = curve_fit(_double_eddy, turns, B1, p0=p0,
                            bounds=([-np.inf, -np.inf, 0.5, -np.inf, 0.5],
                                    [np.inf, np.inf, 500, np.inf, 2000]),
                            maxfev=20000)
        B_inf, A1, tau1, A2, tau2 = popt
        if tau1 > tau2:
            A1, A2 = A2, A1
            tau1, tau2 = tau2, tau1
        B1_pred = _double_eddy(turns, *popt)
        ss_res = np.sum((B1 - B1_pred) ** 2)
        ss_tot = np.sum((B1 - B1.mean()) ** 2)
        r2_double = 1 - ss_res / ss_tot if ss_tot > 0 else 0.0
        _dbl_records.append({
            "run_id": run_id, "I_nom": srow["I_nom"], "branch": srow["branch"],
            "r2_1exp": r2_single, "r2_2exp": r2_double,
            "delta_r2": r2_double - r2_single,
            "tau1_s": tau1 * T_PER_TURN, "tau2_s": tau2 * T_PER_TURN,
        })
    except (RuntimeError, ValueError):
        _dbl_records.append({
            "run_id": run_id, "I_nom": srow["I_nom"], "branch": srow["branch"],
            "r2_1exp": r2_single, "r2_2exp": np.nan,
            "delta_r2": np.nan, "tau1_s": np.nan, "tau2_s": np.nan,
        })

_df_dbl = pd.DataFrame(_dbl_records)
if not _df_dbl.empty:
    print("Double-exponential fit comparison:")
    print(f"{'Run':>4s} {'I [A]':>8s} {'R\\u00b2_1exp':>8s} {'R\\u00b2_2exp':>8s} "
          f"{'\\u0394R\\u00b2':>8s} {'\\u03c41 [s]':>8s} {'\\u03c42 [s]':>8s}")
    print("-" * 62)
    for _, r in _df_dbl.iterrows():
        r2d = f"{r['r2_2exp']:.4f}" if pd.notna(r['r2_2exp']) else "FAIL"
        dr = f"{r['delta_r2']:+.4f}" if pd.notna(r['delta_r2']) else "---"
        t1 = f"{r['tau1_s']:.1f}" if pd.notna(r['tau1_s']) else "---"
        t2 = f"{r['tau2_s']:.1f}" if pd.notna(r['tau2_s']) else "---"
        print(f"{r['run_id']:4.0f} {r['I_nom']:+8.1f} {r['r2_1exp']:8.4f} "
              f"{r2d:>8s} {dr:>8s} {t1:>8s} {t2:>8s}")

    _valid = _df_dbl.dropna(subset=["r2_2exp"])
    if len(_valid) > 0:
        _improved = _valid["delta_r2"] > 0.001
        print(f"\\nSubstantially improved (\\u0394R\\u00b2 > 0.001): "
              f"{_improved.sum()} / {len(_valid)} runs")
        print(f"Mean \\u0394R\\u00b2: {_valid['delta_r2'].mean():.5f}")
else:
    print("No fits available for double-exponential comparison.")"""))

    return cells


# ── main logic ──────────────────────────────────────────────────────

NOTEBOOKS = [
    {
        "dir": "01_with_shims",
        "is_streaming": False,
        "summary_heading": "## 12. Summary Table",
        "export_heading": "## 13. Export to CSV",
    },
    {
        "dir": "02_without_shims",
        "is_streaming": False,
        "summary_heading": "## 12. Summary Table",
        "export_heading": "## 13. Export to CSV",
    },
    {
        "dir": "03_2Hz_afternoon",
        "is_streaming": True,
        "summary_heading": "## 14. Summary Table",
        "export_heading": "## 16. Export to CSV",
    },
    {
        "dir": "04_2Hz_morning",
        "is_streaming": True,
        "summary_heading": "## 14. Summary Table",
        "export_heading": "## 16. Export to CSV",
    },
]


def update_notebook(spec: dict) -> None:
    nb_path = NB_BASE / spec["dir"] / "analysis.ipynb"
    with open(nb_path, encoding="utf-8") as f:
        nb = json.load(f)

    cells = nb["cells"]
    original_count = len(cells)

    # -- Check if already updated --
    if _find_cell_containing(cells, "Eddy-Current Settling Analysis") is not None:
        print(f"  {spec['dir']}: already has eddy-current sections -- skipping")
        return
    if _find_cell_containing(cells, "Higher Harmonics Overview") is not None:
        print(f"  {spec['dir']}: already has higher harmonics section -- skipping")
        return

    # -- Find insertion points --
    summary_idx = _find_cell(cells, spec["summary_heading"])
    export_idx = _find_cell(cells, spec["export_heading"])

    if summary_idx is None:
        # Fallback: search for partial match
        summary_idx = _find_cell_containing(cells, "Summary Table")
    if export_idx is None:
        export_idx = _find_cell_containing(cells, "Export to CSV")

    if summary_idx is None or export_idx is None:
        print(f"  {spec['dir']}: could not find insertion points "
              f"(summary={summary_idx}, export={export_idx}) -- skipping")
        return

    # -- Build new cells --
    higher_cells = build_higher_harmonics_cells()
    eddy_cells = build_eddy_cells(is_streaming=spec["is_streaming"])

    # -- Insert (reverse order to preserve indices) --
    # Eddy cells go before export
    for c in reversed(eddy_cells):
        cells.insert(export_idx, c)

    # Higher harmonics go before summary (which may have shifted)
    # Re-find summary since eddy cells were inserted after it
    for c in reversed(higher_cells):
        cells.insert(summary_idx, c)

    nb["cells"] = cells
    with open(nb_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)

    n_added = len(cells) - original_count
    print(f"  {spec['dir']}: {original_count} -> {len(cells)} cells "
          f"(+{n_added} new)")


def main():
    print("Updating MC62 analysis notebooks...")
    for spec in NOTEBOOKS:
        update_notebook(spec)
    print("\nDone. New cells have empty outputs -- re-run each notebook to populate.")


if __name__ == "__main__":
    main()
